# Generated by Django 3.1.4 on 2020-12-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201205_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='product_id',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], default='Select product', max_length=255),
        ),
    ]
