# Generated by Django 3.1.4 on 2020-12-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201205_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='product_id',
            field=models.CharField(choices=[('Select product', 'Select product'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=255),
        ),
    ]
